spring:
  application:
    name: mongodb-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: music
      repositories:
        enabled: true

server:
  port: 8084


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost