spring:
  application:
    name: zuul-service

server:
  port: 8300

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  prefix: /api
  routes:
    music-catalog:
      path: /music-catalog/**
      serviceId: music-catalog-service